### ISSUE TITLE
New 'advice' category in the RPG module

### ISSUE THREAD

**Issue by MatthewCox** [HubbeKing/Hubbot_Twisted#17]
Like lrrbot's !advice, for general life advice

Suggested by rucdoc, seems to fit best into Hubbot

**Comment by Heufneutje** [comment]
:+1:

**Comment by HubbeKing** [comment]
Adding the functionality to the module and creating a table for it would be fairly simple, but the entire module currently depends on each thing having a number, so this'd have to be the case for advice aswell.

**Comment by HubbeKing** [comment]
Threw together the code in the module for it, I'll have to add a database table manually, will do that this evening.

**Comment by HubbeKing** [comment]
Is now added as +advice.
